function [xi, sumNonMonitoredTime, residualArray] =  wrapLayerSolve(isElasticElement,isRigidElement,rigidBodySetsPerLayer,vertexRigidBody,isBoundaryVertex,isRigidVertex, xi, lambdai, sumNonMonitoredTime, h , numRigids, residualArray,boundaryCompliance,...
                                                                                                                                                        contactResistance,...
                                                                                                                                                        contactCompliance,...
                                                                                                                                                        iterations,...
                                                                                                                                                        layers,...
                                                                                                                                                        runUntilResSmallerThan,...
                                                                                                                                                        computeResiduals,...
                                                                                                                                                        hangingStop,...
                                                                                                                                                        giveUpEnabled,...
                                                                                                                                                        giveUpThreshold,...
                                                                                                                                                        LastLayerGiveUpEnabled,...
                                                                                                                                                        useGravityConstraints,...
                                                                                                                                                        oldp,...
                                                                                                                                                        oldOldp,...
                                                                                                                                                        contactNormals,...
                                                                                                                                                        pointColliders ,...
                                                                                                                                                        contactVertexID,...
                                                                                                                                                        mass,...
                                                                                                                                                        T,...
                                                                                                                                                        unpinnedDOFs,...
                                                                                                                                                        pinnedDOFs,...
                                                                                                                                                        DmInv,...
                                                                                                                                                        perElementXPBDalphaMatrix,...
                                                                                                                                                        perElementXPBDalphaInvMatrix,...
                                                                                                                                                        elementColor,...
                                                                                                                                                        elementDOFs,...
                                                                                                                                                        numColors,...
                                                                                                                                                        f,...
                                                                                                                                                        layersMap,...
                                                                                                                                                        gravityCompliance, ...
                                                                                                                                                        gravity,...
                                                                                                                                                        perElementXPBDBeta) %#codegen
[xi, sumNonMonitoredTime, residualArray] = xpbdLayer2D.layerSolve(isElasticElement,isRigidElement,rigidBodySetsPerLayer,vertexRigidBody,isBoundaryVertex,isRigidVertex, xi, lambdai, sumNonMonitoredTime,h , numRigids, residualArray,boundaryCompliance,...
                                                                                                                                                        contactResistance,...
                                                                                                                                                        contactCompliance,...
                                                                                                                                                        iterations,...
                                                                                                                                                        layers,...
                                                                                                                                                        runUntilResSmallerThan,...
                                                                                                                                                        computeResiduals,...
                                                                                                                                                        hangingStop,...
                                                                                                                                                        giveUpEnabled,...
                                                                                                                                                        giveUpThreshold,...
                                                                                                                                                        LastLayerGiveUpEnabled,...
                                                                                                                                                        useGravityConstraints,...
                                                                                                                                                        oldp,...
                                                                                                                                                        oldOldp,...
                                                                                                                                                        contactNormals,...
                                                                                                                                                        pointColliders ,...
                                                                                                                                                        contactVertexID,...
                                                                                                                                                        mass,...
                                                                                                                                                        T,...
                                                                                                                                                        unpinnedDOFs,...
                                                                                                                                                        pinnedDOFs,...
                                                                                                                                                        DmInv,...
                                                                                                                                                        perElementXPBDalphaMatrix,...
                                                                                                                                                        perElementXPBDalphaInvMatrix,...
                                                                                                                                                        elementColor,...
                                                                                                                                                        elementDOFs,...
                                                                                                                                                        numColors,...
                                                                                                                                                        f,...
                                                                                                                                                        layersMap,...
                                                                                                                                                        gravityCompliance, ...
                                                                                                                                                        gravity,...
                                                                                                                                                        perElementXPBDBeta);
end

